### ISSUE TITLE
Uninstall PiCAST

### ISSUE THREAD

**Issue by Oliviercreativ** [lanceseidman/PiCAST#59]
Hello,
I would like to uninstall PiCAST please. I prefer to start it manually.
I do not find any solutions ...

**Comment by BaldEagleX02** [comment]
I have the same problem. I cannot uninstall PiCAST completely.

**Comment by lanceseidman** [comment]
Unfortunately, due to the changes are done in Raspian, the parameters are no longer the same and the project is no longer working and/or has those modifications sadly.

I have not made any changes to the project since most packages have been updated, which is probably why you're having these issues, but if you could provide what exactly is not being uninstalled, would be great so I could eventually look into it.
